services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - package-service
      - vuln-service

  package-service:
    build:
      context: .
      dockerfile: package-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:pass@package-db:5432/packages
      - JWT_SECRET=supersecret-enterprise-key-2024
      - JWT_ALGORITHM=HS256
    depends_on:
      - package-db
      - redis

  vuln-service:
    build:
      context: .
      dockerfile: vuln-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:pass@vuln-db:5432/vulnerabilities
      - PACKAGE_SERVICE_URL=http://package-service:8001
      - JWT_SECRET=supersecret-enterprise-key-2024
      - JWT_ALGORITHM=HS256
    depends_on:
      - vuln-db
      - redis

  package-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=packages
    volumes:
      - package_data:/var/lib/postgresql/data
      - ./init/package_init.sql:/docker-entrypoint-initdb.d/init.sql

  vuln-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=vulnerabilities
    volumes:
      - vuln_data:/var/lib/postgresql/data
      - ./init/vuln_init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  package_data:
  vuln_data:
