upstream package_service {
    server package-service:8001;
}

upstream vuln_service {
    server vuln-service:8002;
}

server {
    listen 80;

    location /api/v1/packages {
        proxy_pass http://package_service;
    }

    location /api/v1/versions {
        proxy_pass http://package_service;
    }

    location /api/v1/vulns {
        proxy_pass http://vuln_service;
    }

    location /login {
        proxy_pass http://package_service;
    }

    location /health {
        return 200 '{"status":"UP"}';
        add_header Content-Type application/json;
    }
}
